#!/bin/bash
#
# Shell script to generate Riverbed inventory using the Riverbed API
# The data is then parsed through an awk script which formats the data
# nicely :)
#
# Start

source=/etc/hosts
tmp=/tmp/inventory-rvb-tmp
edit=/tmp/rvb-edit
format=/usr/local/bin/inventory-rvb-awk

clear
echo '--------------------------------------------------------'
echo 'Grabbing data from the Riverbed devices via the API.....'
echo '--------------------------------------------------------'

for i in `egrep rb1 $source | awk '{print $2}'`; do
    curl -s https://$i:9443/api/common/1.0/info -k >> $tmp;
done

for host in `egrep 'rb' $source | awk '{print $3}'`; do
    device=`egrep $host $tmp | awk '{print $2}' | sed 's/"//g' | sed 's/,//g'`
    model=`egrep -A4 $host $tmp | egrep 'model' | awk '{print $2}' | sed 's/"//g' | sed 's/,//g'`
    serial=`egrep  -A4 $host $tmp | egrep 'serial' | awk '{print $2}' | sed 's/"//g' | sed 's/,//g'`
    code=`egrep -A4 $host $tmp | egrep 'version' | awk '{print $2}' | sed 's/"//g' | sed 's/,//g'`
    echo $device $model $serial $code | awk 'NF' >> $edit
done;

$format $edit
rm $tmp
rm $edit
